// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJqp-KAt6-r4p8L4wB2XDpgJwMO_pCRoA',
    appId: '1:273514805049:web:c93129d748e6b83478dae8',
    messagingSenderId: '273514805049',
    projectId: 'fyp-ecardio',
    authDomain: 'fyp-ecardio.firebaseapp.com',
    storageBucket: 'fyp-ecardio.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb6sxTrEY-IjmkK_cvh_IctOHQB1pbJFE',
    appId: '1:273514805049:android:1d4e80b8c69c8f1778dae8',
    messagingSenderId: '273514805049',
    projectId: 'fyp-ecardio',
    storageBucket: 'fyp-ecardio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyaDl6UmM2DkszUTceP1zdjHOv9dkgNTo',
    appId: '1:273514805049:ios:4145b734f14ea93078dae8',
    messagingSenderId: '273514805049',
    projectId: 'fyp-ecardio',
    storageBucket: 'fyp-ecardio.appspot.com',
    iosBundleId: 'com.example.ecardio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyaDl6UmM2DkszUTceP1zdjHOv9dkgNTo',
    appId: '1:273514805049:ios:eef431b9cfd88a0478dae8',
    messagingSenderId: '273514805049',
    projectId: 'fyp-ecardio',
    storageBucket: 'fyp-ecardio.appspot.com',
    iosBundleId: 'com.example.ecardio.RunnerTests',
  );
}
